= Edit Names of Schema Elements

When you add APIs to the unified schema, can rename fields, types, and query methods so they're more useful to those consuming the unified schema, or so you can resolve conflicts between elements.

If you attempt to rename a type in an API that is merged with a type in the unified schema, you will undo the merge. Likewise, modifying the name of a field that you've configured as a primary key will break the link or merge associated with that primary key. When renaming fields or query methods, ensure that you are not breaking existing collaborations on those elements.

Before editing the name of an element, be sure to xref:manage-elements-visibility.adoc[make it visible].

To edit the name of a schema element:

. Navigate to object type, field, or method, and click *Rename*.
. In the *Change to:* field, add the new name, and click *Confirm*.
. If you want to reset to the element to its default, click *Rename* again, and then click *Reset name to default*.
