= Edit APIs In Unified Schema

As you develop your unified schema, you can make changes to the APIs you've added to it. You can edit APIs to resolve conflicts and other issues, or remove APIs from the unified schema as they become deprecated.

== Undo Merges Between Object Types

You can undo merges between object types as needed. For example, if you want to merge an object type that has already been merged with a type in the unified schema, you'll need to undo the current merge and then create a new one merge.

Undoing a merge could break existing queries.

If you undo a merge between an object type and a type in the unified schema, you'll need to rename that object type (and its query method, if merged). DataGraph will display  a conflict until the type (and its query method) are renamed or merged again.

Additionally, nullable fields return to their original state after you undo a merge. For example: if a field in a type was non-nullable, but as a result of a merge became nullable, then the field will go back to being non-nullable after you  undo the merge.

. Click *List of APIs added* and select the API that contains the merged object type.
. In the API schema navigation, select the object type and scroll to the *Merge* pane.
. Click *Undo merge*.
. Click *Apply Changes*.


== Remove Linked Fields Between Object Types

You can remove linked fields between object types if the link is no longer needed.

A field can be linked to only one other field at a time. So, if you have a linked field but want to link it to a different field, you'll need to first remove the original link.

. Click *List of APIs added* and select the API that contains the object type with the linked field.
. In the API schema navigation, select the object type with the linked field, and scroll to the *Link to another type* pane.
. Find the link you want to remove and click *>* to open the link details.
. Click *Remove Link*.
. Click *Save*, and then click *Apply Changes*.

== Disable Collaboration for an Object Type

If you no longer want an object type to provide its fields to other types, you can disable collaboration for that type. Disabling collaboration on an object that is merged with another type in the unified schema will break the merge.

. Click *List of APIs added* and select the API that contains the object type for which you want to disable collaboration.
. In the API schema navigation, select the object type.
. In the *Collaboration permissions* pane, clear the selection for *Allow collaboration for this type (Extend this type).*
. When prompted confirm you want to disable collaboration for the object type. Click *Undo merge and disable collaboration*.

== Remove an API from the Unified Schema

You can remove APIs from the unified schema as needed.

Removing an API from the unified schema will break any merges, links, and existing queries.

. Click *List of APIs added* and select the API that you want to remove.
. Click *Remove API*, and then click *Apply Changes*.
