= Anypoint DataGraph Hosting Options and Permissions

Anypoint DataGraph supports the following Anypoint Platform hosting options and permissions settings.

=== Supported Control Plane Hosting Options

Anypoint DataGraph beta release is available for US and EU clouds control plane hosting.

=== Supported Runtime Plane Hosting Options

Anypoint DataGraph must connect to the destination URL you provide when adding an API to the unified schema. You don't need to make any extra configurations on your runtime plane if you meet any of the following scenarios:

* Your API implmentations run on CloudHub.
* Your API implementations run on standalone instances and are connected to an Anypoint Virtual Private Cloud (Anypoint VPC).
* Your API implementations run on any runtine plane hosting option and are public.

If your API instances run on standalone instances, are not public, and are not connected to Anypoint VPC, you must first pair your standalone runtimes to Anypoint VPC. See https://docs.mulesoft.com/runtime-manager/to-request-vpc-connectivity[Request Anypoint VPC Connectivity to Your Network^] for more information.

== Permissions For Anypoint DataGraph

DataGraph provides access management permissions so you can meet your organization's requirements and at the same time drive collaboration across teams.

Permissions for DataGraph are independent of permissions for other Anypoint platform products.

One business group can only have one graph per environment.

The following permissions are available per business group per environment:

[%header%autowidth.spread]
|===
|Permission |Description
|Admin |Permission to contribute, consume, promote, and operate the unified schema
|Contribute a| Permission to:

* Add source APIs to the unified schema
* Edit any source API that has been added to the unified schema
* Request access to and run queries with proper credentials
* Promote APIs to and from the environment
* View query traces in real time while running queries from the UI
|Consume a|Permission to:

* View and explore the unified schema
* Request access to and make data requests from the UI
|Operate |Permission to view customer-facing logs
|===

== See Also

* xref:general::intro-platform-hosting.adoc[Anypoint Platform Hosting Options]
* xref:access-management::roles.adoc[Access Management Roles]
* xref:access-management::managing-permissions.adoc[Access Management Managing Permissions]
