= Overview

Anypoint DataGraph enables you to leverage the existing capabilities of your application network to drive productivity by unifying all the data within your application network in a data graph. As a developer, you can dynamically query the graph and consume the fields that you need to create new connected experiences. You can improve your productivity and reduce operational costs by discovering and reusing the existing data in your application network.

With Anypoint DataGraph you can:

* Dynamically query data from a unified graph
* Explore your application network from a single UI
* Discover, reuse, and serve information from your application network without writing new code

Note that Anypoint DataGraph is a beta release and is available for US and EU clouds.

== How Anypoint DataGraph Works

Every time you add a new API to your application network, Anypoint Platform stores it as a graph of metadata. Anypoint DataGraph enables you to connect those graphs into one unified data graph that runs as a single SaaS endpoint and contains and links all of the fields contained within all of the APIs. As a result of this linking, you can query across the underlying APIs without understanding all of the relationships among API data or where specific capabilities exist.

For example, consider an organization using the following APIs:

* An orders API that provides information about specific purchase orders
* A shipment API that provides shipment information for each purchase order
* A products API that provides product information and specifications

The organization wants to create a mobile application to provide specific order status details for its customers.

To deliver this mobile application, API developers must build a new API that identifies all orders for a customer, finds the products in those orders, identifies each shipment record, and finds delivery dates and tracking numbers. The enterprise architect must first grant the developers access to each necessary API, and then manage and secure this API after the developers build and deliver it.

Now consider that this organization also wants to provide a web application to a warehouse stocking agent for all existing orders of each product. The team would need to go through a similar development to deliver it.

By using Anypoint DataGraph, the organization does not need to create a new API for every new business requirement. The enterprise architect can discover the existing order, shipment, and product APIs and add them to the consolidated graph provided by Anypoint DataGraph. Developers can then request access to the graph and query the data that they need, reusing existing data.
