= Permissions For Anypoint DataGraph

DataGraph provides access management permissions so you can meet your organization's requirements and at the same time drive collaboration across teams.

Permissions for DataGraph are independent of permissions for other Anypoint platform products.

The following permissions are available per business group per environment:

[%header%autowidth.spread]
|===
|Permission |Description
|Admin |Permission to contribute, consume, and operate the unified schema
|Contribute a| Permission to:

* Add source APIs to the unified schema
* Edit any source API that has been added to the unified schema
* Request access to and run queries with proper credentials
* Promote APIs to and from the environment
* View query traces in real time while running queries from the UI
|Consume a|Permission to:

* View and explore the unified schema
* Request access to queries and make data requests from the UI
|Operate |Permission to view customer-facing logs
|===

To contribute to the unified schema, you need to have the *Exchange Viewers* permission for the business group from which you want to add APIs. Refer to xref:exchange::to-set-permissions.adoc[Set User Access Permissions] for more information.

==Additional Resources

For more information on setting DataGraph SLA tiers and managing contracts, refer to xref:api-manager::datagraph-landing-page.adoc[DataGraph Administration] in the API Manager documentation.

For instructions on setting up user permissions and roles for DataGraph, refer to xref:access-management-users.adoc#granting-permissions-and-roles-to-users[Granting Permissions and Roles to Users]
