= Potential Errors When Generating an API Schema

When you add a new API to your unified schema, Anypoint DataGraph generates an API schema for it. However, not all features of an API specification are successfully generated into an API schema.

Anypoint DataGraph does not translate the following parts of an API specification into an API schema:

* Non-GET operations
* Requests with a `Media type` value other than `application/json`
* Responses with a `Media type` value other than `application/json`
* Response payloads with any of the unsupported types `Schema`, `File`, `Tuple`, `Matrix`, `Nil`, or arrays of any of these types
* `uri params`, `query params`, and `headers` with types other than scalars or scalar array
* Endpoints of required `params` of unsupported types
* `union` types with members other than `objects` and `nils`
* JSON schema keywords `if`, `then`, and `else`

If your API specification is composed of only unsupported parts, Anypoint DataGraph does not generate an API schema and throws a *Validation failed* error.

== Additional Resources

* xref:resolve-conflicts.adoc[Resolve Conflicts and Merge Inconsistencies]
* xref:edit-schema.adoc[Edit Your API Schema for Addition to the Unified Schema]
