= Supported Anypoint Platform Hosting Options

Anypoint DataGraph beta release is supported by the following Anypoint Platform hosting options.

== Supported Control Plane Hosting Options

Anypoint DataGraph beta release is available for US and EU clouds control plane hosting.

== Supported Runtime Plane Hosting Options

Anypoint DataGraph must connect to the destination URL you provide when adding an API to the unified graph. You don't need to make any extra configurations on your runtime plane if you meet any of the following scenarios:

* Your API implmentations run on CloudHub.
* Your API implementations run on standalone instances and are connected to an Anypoint Virtual Private Cloud (Anypoint VPC).
* Your API implementations run on any runtine plane hosting option and are public.

If your API instances run on standalone instances, are not public, and are not connected to Anypoint VPC, you must first pair your standalone runtimes to Anypoint VPC. See https://docs.mulesoft.com/runtime-manager/to-request-vpc-connectivity[Request Anypoint VPC Connectivity to Your Network^] for more information.