= Supported Authentication Methods

You must set up authentication so Anypoint DataGraph can access the GET endpoints of the APIs that you add to the unified schema. Authentication allows Anypoint DataGraph to make requests to those APIs when you run queries.

When adding a new API schema to the unified schema, or when promoting an API schema to another environment, you must configure one of the following authentication methods:

* *No Auth*
+
Use if your API is public.

* *Basic Auth*
+
Use if you authenticate to your API using the basic authentication header, or a username and password.
+
For example:
+
[source,CURL,linenums]
--
curl "http://localhost/myResource" -u myUser:myPassword
--
+
or
+
[source,CURL,linenums]
--
curl GET 'http://localhost/myResource' \
--header 'Content-Type: application/json' \
--data-raw '{
  "username": "myUser",
  "password": "myPassword"
}'
--

* *Pass-through*
+
Use if you authenticate to your API by passing authorization headers.
+
You must supply a:

** *Query Header Name*: The name of the HTTP header sent with the initial query to the unified schema. 
** *API Header Name*: The header name passed through to the underlying API. This is useful if you want to rename the query header before passing it through to the underlying API. 

* *Client ID enforcement via headers*
+
Use if you authenticate to your API by passing `client_id` and `client_secret` headers.
+
For example:
+
[source,CURL,linenums]
--
curl "http://localhost/myResource" -H "client_id:1234" -H "client_secret:abcd"
--
* *Client ID enforcement via query parameters*
+
Use if you authenticate to your API by passing `client_id` and `client_secret` query params.
+
For example:
+
[source,CURL,linenums]
--
curl "http://localhost/myResource?client_id=1234&client_secret=abcd"
--
* *Custom*
+
Use if you authenticate to your API using custom header parameters and values.

Any other authentication methods to access your added API, such as custom OAuth implementations or short-lived token methods, are not supported.

== Additional Resources

* xref:add-api-to-unified-schema.adoc[]
* xref:promote-api.adoc[]
* xref:add-api-to-unified-schema.adoc#change-the-authentication-method-for-an-api-aded-to-the-unified-schema[Change the Authentication Method for an API Added to the Unified Schema]
